### ISSUE TITLE
Slow Pageloads

### ISSUE THREAD

**Issue by mlucool** [ryantam626/jupyterlab_code_formatter#293]
**Checklist prior to opening an issue**
- [X] I have followed fully the installation steps laid out in the documentation site.
- [X] I have restarted jupyterlab.
- [X] I have read the FAQ section in the documentation site.

**Describe the bug**
Using this plugin adds ~1.5-2s of pageload time for my setup.

**Additional context**
I narrowed this down by looking at the network tab. This stems from loading the `my-jupyterlab.foo.com/jupyterlab_code_formatter/formatters` route which in Jupyter both blocks pageload and (I think) blocks the server as it is single threaded. This network call leads to [this code](https://github.com/ryantam626/jupyterlab_code_formatter/blob/ace5fb442965eebd1b950df1f3dda284ec8dc8d0/jupyterlab_code_formatter/handlers.py#L73) being called. 

Below is a reproducer of the longest part of the call, which on my setup takes ~1.6s:
```
%%time

from jupyterlab_code_formatter.formatters import SERVER_FORMATTERS


json.dumps(
    {
        "formatters": {
            name: {
                "enabled": formatter.importable,
                "label": formatter.label,
            }
            for name, formatter in SERVER_FORMATTERS.items()
        }
    }
)
```

Digging deeper, the problem is `formatter.importable` does not act like property, but function which often calls [this expensive function](https://github.com/ryantam626/jupyterlab_code_formatter/blob/ace5fb442965eebd1b950df1f3dda284ec8dc8d0/jupyterlab_code_formatter/formatters.py#L221). Each call in my setup takes ~300ms.

I believe if `importib.reload` is called at most once per get call, that would save 4/5 of the cost. In my setup, I'm ok with this not detecting new instances installed/uninstalled after lab is started.

Would you be open to a PR that:
1. Reduced the times importib is called per `get`
2. Allowed users to opt for a cached version for this getter

**Comment by krassowski** [comment]
In addition of allowing users to opt in for a cached version, the implementation could be reworked; indeed reloading `pkg_resources` each time is expensive, especially because it is wasteful - we only need to know about a single package:

https://github.com/ryantam626/jupyterlab_code_formatter/blob/ace5fb442965eebd1b950df1f3dda284ec8dc8d0/jupyterlab_code_formatter/formatters.py#L221-L225

Since `pkg_resources` is deprecated in favour of `importlib` (see https://github.com/pypa/setuptools/issues/2531) one solution would be to replace it with:

```python
def is_importable(pkg_name: str) -> bool:
    return importlib.util.find_spec(pkg_name) is not None
```

If sticking with `pkg_resources` for now is preferable,  `pkg_resources._initialize_master_working_set` could be of use (see https://github.com/pypa/setuptools/issues/373) but it yields only a small improvement:

- `importlib.reload` (curent): 2.13 s
- `_initialize_master_working_set`: 1.97 s
- `importlib.util.find_spec`: 874 ms
