### ISSUE TITLE
404 on jupyter image

### ISSUE THREAD

**Issue by smiecj** [ryantam626/jupyterlab_code_formatter#310]
Hi, I just run jupyter container **docker run -it -p 8888:8888 jupyter/scipy-notebook:lab-3.6.3** , then install formatter:

```
pip install jupyterlab-code-formatter
pip install black
pip install yapf
pip install isort
pip install autopep8
```

But when click "format" button, it announce 404 problem:
<img width="981" alt="image" src="https://github.com/ryantam626/jupyterlab_code_formatter/assets/14009307/0df814d4-9d4c-4657-9aab-b40742ac08a4">

curl param copy from chrome:
```
curl 'http://.../jupyterlab_code_formatter/format?1684310976887' \
  -H 'Accept: */*' \
...
  --data-raw '{"code":["print(123)"],"notebook":true,"formatter":"isort","options":{"multi_line_output":3,"include_trailing_comma":true,"force_grid_wrap":0,"use_parentheses":true,"ensure_newline_before_comments":true,"line_length":88}}' \
  --compressed \
  --insecure
```

Maybe my installation steps have some problem? Thanks in advance

**Comment by ryantam626** [comment]
Hi, thanks for the report.

So to recap, you are doing 
```bash
docker run -it -p 8888:8888 jupyter/scipy-notebook:lab-3.6.3
```

then within jupyterlab itself you do
```bash
pip install jupyterlab-code-formatter
pip install black
pip install yapf
pip install isort
pip install autopep8
```
?


I know what's the issue here if that's the case. You haven't done the step outlined [here](https://jupyterlab-code-formatter.readthedocs.io/#:~:text=This%20plugin%20includes%20a%20server%20plugin%2C%20as%20suck%20you%20will%20need%20to%20restart%20JupyterLab%20if%20you%20have%20followed%20the%20above%20steps%20while%20it%E2%80%99s%20running.), you either need to modify the entrypoint such that these pypi packages are installed before jupyterlab is started or build upon the docker image you are using.

**Comment by smiecj** [comment]
Thanks! After I add example formatter like [this](https://jupyterlab-code-formatter.readthedocs.io/custom-formatter.html#adding-custom-formatters) in config.py, it fixed.
